### ISSUE TITLE
Type Checker regards Type Constructor as Type in some cases.

### ISSUE THREAD

**Issue by NoahStoryM** [racket/typed-racket#1170]
### What version of Racket are you using?
`v8.3.0.8 [cs]`

### What program did you run?
```
#lang typed/racket/base

(define-type (Identity-0 A) A)
(ann 123 (Identity-0 Natural))

(define-type Identity-1 (All (A) A))
(ann 123 (Identity-1 Natural))

```

### What should have happened?
print:
```
123
123
```

### If you got an error message, please include it here.
```
draft.rkt:7:9: Type Checker: parse error in type;
 bad syntax in type application: expected a type constructor
  given a type: Identity-1
  in: (Identity-1 Natural)
  location...:
   draft.rkt:7:9
  context...:
   .../private/runtime.rkt:80:24: temp7845
   .../private/parse.rkt:559:26
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt:112:0: tc-expr/check
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:414:0: type-check
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:653:0: tc-module
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/tc-setup.rkt:101:12
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/typed-racket.rkt:22:4
```

**Comment by NoahStoryM** [comment]
### What should have happened?
```
> (:kind (All (A) A))
(-o * *)
```

### In fact
```
> (:kind (All (A) A))
*
```

**Comment by samth** [comment]
This is intentional. There are three possibilities for types like `(All (A) A)`. 
1. They're types. That's the current design, and the usual way systems with first-class polymorphism work.
2. They're type constructors, with kind `(-> * *)`. That would make your examples work, but then this would not work: `(Listof (All (A) (-> A Integer))` because `Listof` has the kind `(-> * *)`. 
3. They're both in some way. That how it used to work, and it was not good. You could imagine a more restricted version this where first-order uses of polymorphic types as type constructors did instantiation, but that seems more confusing than helpful, especially since I've never seen a case where someone really wanted to use it in both way.

Note that this is also how Haskell works, for example:
```
Prelude> :k (forall a. a -> Integer)
(forall a. a -> Integer) :: *
```

**Comment by NoahStoryM** [comment]
Thank you! I guess I understand something about the difference between type constructors and polymorphic types.

But I still have a little doubt. Apart from polymorphic types of functions (for example `(All (A) (-> ...))`), are there other places where `All` is needed?

For example, `(All (A B) (Pair A B))`, I can't imagine how this type should be used, and what its value should be.

**Comment by capfredf** [comment]
types like the one you gave are inhabitable. For example, [] in haskell has type:

```
[] : [a]
```

or you can roll your own:
```
Prelude> data MyPair a b = Cons a b | Null
Prelude> :type Null
Null :: MyPair a b
```

As for why `(ann null (All (A) (Listof A))` does not work in TR, I guess it is a bug in where subtyping is handled, given the type-checker is happy about:

```
(define #:forall (A) (foo) : (Listof A)
  null)
```

**Comment by NoahStoryM** [comment]
Thanks!
