### ISSUE TITLE
`check-eq? (hasheq) (hasheq)` fails

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#1357]
### What version of Racket are you using?
`v8.10 [cs]`

### What program did you run?
```racket
#lang typed/racket/base
(require typed/rackunit)
(check-eq? (hasheq) (hasheq))
```

### What should have happened?
Test succeeds like with untyped `check-eq?`

### If you got an error message, please include it here.
```
FAILURE
name:       check-eq?
location:   racket-mode-repl:?:?
actual:     '#hasheq()
expected:   '#hasheq()
```

Intriguingly, `(check-eq? (hash) (hash))` is ok.

**Comment by sorawee** [comment]
This works though...

```
#lang typed/racket/base
(require typed/rackunit)
(check-true (eq? (hasheq) (hasheq)))
```

**Comment by sorawee** [comment]
A more minimal example

```
#lang racket

(module no-req typed/racket/base
  (define x '())
  (eq? x x) ;=> #t

  (define y '(1 2))
  (eq? y y) ;=> #t

  (define z (hasheq))
  (eq? z z)) ;=> #t

(module req typed/racket/base
  (require/typed racket
                 [eq? (-> Any Any Any)])

  (define x '())
  (eq? x x) ;=> #t

  (define y '(1 2))
  (eq? y y) ;=> #f

  (define z (hasheq))
  (eq? z z)) ;=> #f

(require 'no-req)
(require 'req)
```

**Comment by sorawee** [comment]
Probably something is needed to be changed here. 

https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/utils/any-wrap.rkt#L142-L150

**Comment by sorawee** [comment]
I think the `(not (hash-eqv? e)) (not (hash-eq? e))` can be removed, and this would fix this issue. We can do that since we already use `hash-map/copy`, which retains the key comparison and kind. The conditions were added when we [unconditionally produce](https://github.com/racket/typed-racket/commit/2330c5aff152acb0e4b2a00bf9db5ef427e41ceb) a new hash via `for/hash`, but we no longer do that.
