### ISSUE TITLE
Occurrence typing discards polymorphic information

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#147]
This program doesn't typecheck:

```racket
(: f (All [a] (U a (Vectorof a)) -> a))
(define (f v)
  (if (vector? v)
      (f (vector-ref v 0))
      v))
```

In the first branch of the `if`, the type of `v` is `VectorTop` when it should be `(Vectorof a)`. This happens with all polymorphic types.

Interestingly, the type of `v` in the second branch *is* just `a`, as it should be, so TR is correctly understanding that the first branch covers the `Vectorof` case.

**Comment by samth** [comment]
What if a was instantiated at Vectorof String?

**Comment by AlexKnauth** [comment]
To put what Sam said another way, this works fine:
```racket
#lang typed/racket
(: f (All [a] (U (Listof a) (Vectorof a)) -> (Listof a)))
(define (f v)
  (if (vector? v)
      (f (list (vector-ref v 0)))
      v))
```
The difference is that here it knows that when it's a vector it will never be a `(Listof a)`, but in this:
```racket
(: f (All [a] (U a (Vectorof a)) -> a))
(define (f v)
  (if (vector? v)
      (f (vector-ref v 0))
      v))
```
If `vector?` produces true, then `v` could still have the type `a` which could be a vector that contains a value other than `a`.  That's why this doesn't, and shouldn't, type-check.

**Comment by lexi-lambda** [comment]
Hmm, yes, you're both right. I guess I'd need to wrap the plain `a` case to avoid running into this problem.
