### ISSUE TITLE
Particular instances of struct in define-type

### ISSUE THREAD

**Issue by malcolmstill** [racket/typed-racket#182]
I discussed this with samth on #racket but thought I'd reproduce it here in case anyone else was curious.

In Typed Racket the following type checks: 
```
(define-type cheese (U 'brie 'cheddar))

(: cheesy (cheese -> cheese))
(define (cheesy c)
  c)

(cheesy "brie")
```

Rather than using a primitive in the union, we might want to use a struct. The following type checks:
```
(struct container ([value : String]))
(define-type cheese2 (U (container "brie")
                        (container "cheddar")))

(: cheesy2 (cheese2 -> cheese2))
(define (cheesy2 c)
  c)
```

However, when we actually call `cheesy2` the type checker rejects it:
```
(cheesy2 (container "brie"))
```

```
 Type Checker: cannot apply a non-polymorphic type: container in: (container "brie")
```

samth explained that by parameterising container can make this work:

```
(struct (a) container ([value : a]))
(define-type cheese2 (U (container "brie")
                        (container "cheddar")))

(: cheesy2 (cheese2 -> cheese2))
(define (cheesy2 c)
  c)
```

It doesn't however work straight off with the following:
```
(cheesy2 (container "brie"))
```

```
Type Checker: Polymorphic function `container1' could not be applied to arguments:
Argument 1:
  Expected: a
  Given:    String

Result type:     (container a)
Expected result: cheese2
 in: (container "brie")
```

Someone else mentioned using a `cast` which does work but produces a run-time error when a container is passed that isn't a `cheese2`:
```
(cheesy2 (cast (container "brie") cheese2))
```

samth mentioned using some sort of annotation to get this to check but I don't know how.

My questions are:
- How do I call `cheesy2` without using `cast` with `container` being parameterised?
- Why is it not possible to use a specific unparameterised `container` (say `(container "brie")`) in `define-type`? Will it be possible in the future?

**Comment by AlexKnauth** [comment]
On Aug 18, 2015, at 5:56 PM, Malcolm Still <notifications@github.com> wrote:

> I discussed this with samth on #racket but thought I'd reproduce it here in case anyone else was curious.
> 
> In Typed Racket the following type checks:
> 
> (define-type cheese (U 'brie 'cheddar))
> 
> (: cheesy (cheese -> cheese))
> (define (cheesy c)
>   c)
> 
> (cheesy "brie")
> Rather than using a primitive in the union, we might want to use a struct. The following type checks:
> 
> (struct container ([value : String]))
> (define-type cheese2 (U (container "brie")
>                         (container "cheddar")))
> 
> (: cheesy2 (cheese2 -> cheese2))
> (define (cheesy2 c)
>   c)
This should raise that error about not being able to apply the `container` type here, but apparently that error is delayed.

The struct declaration defines `container` as a concrete type, not a type constructor, so trying to use it as a typed constructor should be an error, and it is, but it's delayed.

The "correct" way to write that would be:
```racket
(define-type cheese2 (U container container))
```
But of course that's silly, and allows all strings in the container, not just those two cheeses.
> However, when we actually call cheesy2 the type checker rejects it:
> 
> (cheesy2 (container "brie"))
>  Type Checker: cannot apply a non-polymorphic type: container in: (container "brie")
> samth explained that by parameterising container can make this work:
> 
> (struct (a) container ([value : a]))
> (define-type cheese2 (U (container "brie")
>                         (container "cheddar")))
> 
> (: cheesy2 (cheese2 -> cheese2))
> (define (cheesy2 c)
>   c)
> It doesn't however work straight off with the following:
> 
> (cheesy2 (container "brie"))
> Type Checker: Polymorphic function `container1' could not be applied to arguments:
> Argument 1:
>   Expected: a
>   Given:    String
> 
> Result type:     (container a)
> Expected result: cheese2
>  in: (container "brie")
> Someone else mentioned using a cast which does work but produces a run-time error when a container is passed that isn't a cheese2:
> 
> (cheesy2 (cast (container "brie") cheese2))
You don't what to use cast here, what you probably want is
```racket
(cheesy2 (ann (container "brie") cheese2))
```
Which is what samth probably meant.

Or another way:
```racket
(cheesy2 ((inst container "brie") "brie"))
```
> samth mentioned using some sort of annotation to get this to check but I don't know how.
> 
> My questions are:
> 
> How do I call cheesy2 without using cast with container being parameterized?

One way I suppose would be doing this:
```racket
#lang typed/racket
(struct container ([value : (U "brie" "cheddar")]))
(define-type cheese2 container)

(: cheesy2 (cheese2 -> cheese2))
(define (cheesy2 c)
  c)
```
But that would mean that `container` can only ever contain cheeses.

> Why is it not possible to use a specific unparameterised container (say (container "brie")) in define-type? Will it be possible in the future?

I asked this question before, and the answer was no:
Question:
http://lists.racket-lang.org/users/archive/2014-April/062261.html
Answer:
http://lists.racket-lang.org/users/archive/2014-April/062266.html

It turns out that what I was really looking for was bounded polymorphism, so that you could have the container struct be polymorphic while still constraining the type to strings, but typed racket doesn't support that.
It's possible that bounded polymorphism could be added in the future though.

**Comment by samth** [comment]
@AlexKnauth explains the issues here very well.

Here's a working version of the code:

```
#lang typed/racket

(struct (a) container ([value : a]))
(define-type cheese2 (U (container "brie")
                        (container "cheddar")))

(: cheesy2 (cheese2 -> cheese2))
(define (cheesy2 c)
  c)

(cheesy2 (container (ann "brie" "brie")))
```

The fact that `(ann (container "brie") cheese2)` doesn't work is a bug, which I'll open separately.
