### ISSUE TITLE
Problem in sources included in some typed racket docs

### ISSUE THREAD

**Issue by Blaisorblade** [racket/typed-racket#207]
All red messages in this page [1] appear to be unintended execution failures.
http://docs.racket-lang.org/ts-guide/typed-untyped-interaction.html#%28part._.Protecting_.Typed-.Untyped_.Interaction%29

Beyond the immediate issue, both here and in racket/racket#1078: Does Scribble support assertions that fail the build, to try harder to prevent this?

One could add assertions when fixing docs that break due to breakage in interactions — or, in the extreme case, add the expected output, and ensure the build fails on a mismatch. This would have caught racket/racket#1078, at the cost of more maintenance effort (maybe too much).

(Originally reported as racket/racket#1079).

**Comment by takikawa** [comment]
This was already fixed in prelease versions by ca46d80189058d612d0ecbae650dba59d8dc7546 and associated other commits in Scribble. I don't think Scribble comes with any built-in support for that kind of thing, especially because in some cases you do want error messages to appear to illustrate something. Thanks.
