### ISSUE TITLE
define-new-subtype should be flag as unstable

### ISSUE THREAD

**Issue by andmkent** [racket/typed-racket#216]
@samth and I believe a needed feature in TR is support for path-elements/fields which do not correspond to actual runtime values --- phantom-fields (similar perhaps to phantom types in Haskell). These would allow for many new features to be implemented as libraries instead of extensions to TR, such as the recent addition of define-newtype (Distinction in the TR internals).

Because of this, I think we should flag the define-new-subtype feature as experimental or unstable before this next release, and possibly require it to be explicitly imported(?), so that the future library implementation is not obligated to be 100% backwards compatible (although of course it would strive to be 100% compatible with the original implementation as much as possible, but we wouldn't want to be stuck supporting both implementations outright in order to avoid breaking programs).

Thoughts?

**Comment by samth** [comment]
@takikawa @stamourv @AlexKnauth what do you think?

**Comment by stamourv** [comment]
That sounds like a good plan to me. I'm all for expressing features in terms of other features. :)

**Comment by takikawa** [comment]
That sounds reasonable to me, but I don't quite understand the proposed phantom field feature and how it would help express these other things. I'd be curious to find out more.

**Comment by lexi-lambda** [comment]
@takikawa The Haskell wiki has a reasonably easy to read article on phantom types: https://wiki.haskell.org/Phantom_type

The idea is that by creating an extra parameterized type that does not exist anywhere except the type system (hence the term "phantom type"), extra information can be encoded into the type system that can make two types incompatible but represent the same actual data.

I am frequently reminded of Joel Spolsky's [Making Code Look Wrong](http://www.joelonsoftware.com/articles/Wrong.html) because phantom types can enforce the sort of invariants described in that blog post. They're also used for things in Haskell like the ST monad, which allows local mutation while still keeping the overall system pure, so IO doesn't "infect" the rest of the call stack. That use case is less relevant in Racket, but I think they're quite likely to be useful, all the same.

I'm not really involved in this issue, so I won't comment on it too much, but I think the idea seems sound, and I look forward to having another tool in the Typed Racket toolbox. :smile:

**Comment by andmkent** [comment]
Okay, let's say we had refinement types in our toolbox for a moment... with those we can have types which talk about the fields of objects/values:

```racket
(Refine [p : (Pairof Any Any)] 
      (or (and ((car p) -: Int)  ((cdr p) -: Int))
          (and ((car p) -: Bool) ((cdr p) -: Bool))))
```

So here we have a pair of ```Any``` with some propositions that refer to the fields of the pair, namely that either the ```car``` and ```cdr``` are both of type ```Int``` or they're both of type ```Bool``` (this particular example is silly, in that it could more simply be a union, but you get the idea, we can refer to fields (i.e. Path Elements in the implementation)).

Those fields refer to _actual_ run-time values that we can access with the functions ```car``` and ```cdr```. But now let's imagine we had a way of declaring fields which _did not_ correspond to any value that is accessible at run-time. Maybe we want to talk about the ```distinction``` field of a value in order to specify that some value which has type ```Real``` we wish to distinguish as specifically representing radians _without_ actually changing the runtime representation (i.e. we still want reals floating around!). Today, we could do this with the new feature we have which defines new distinct subtypes:

```racket
(define-new-subtype Radians (radians Real))
(define r : Radians (radians 0))
```

What I am suggesting is that we could do this with _phantom fields_ as well (and perhaps _phantom field_ is not the best name---just punning off the similarity to phantom types for now):

```racket
(define-phantom-field distinction)
(define-type Radians (Refine [r : Real] ((distinction r) -: 'radian))
(define r : Radians 0)
```

Now, I'm fudging a few details a little (_no idea_ what the best syntax etc for this would be) but the essence is you could define Radians to be just regular Reals where their 'distinction' field is of type 'radian. This 'distinction' field of course does not correspond to any actual runtime value or data, but is just a _phantom field_; it only exists in the type system (as @lexi-lambda described for phantom types). The goal is that phantom fields and regular fields (like car and car) could be treated the _same_ in the type checker (and the thought is these phantom fields could be used to implement lots of other related features).

Does that make sense? (I'm still trying to figure out how to describe this effectively)

**Comment by AlexKnauth** [comment]
Even if `define-new-subtype` can be implemented in terms of more general constructs, it would still have the same meaning, and the same syntax, so I don't see how it would change to be backwards incompatible. Why would it have to be marked as unstable? 

BTW, that's why I didn't expose the `Distinction` type, because I was thinking that it could eventually be defined in terms of a more general construct. If these phantom fields and path-elements are that more general construct, then that's great! So the implementation details of `define-new-subtype` will change to use this, but the "interface" will remain the same.

**Comment by AlexKnauth** [comment]
Actually, I could extend `define-new-subtype` to allow arguments to the type, like:
```racket
(define-new-subtype (Form-Data a) (form-data String))
```
Which would be the equivalent of `newtype FormData a = FormData String` in https://wiki.haskell.org/Phantom_type#Simple_examples . This could be used to enforce invariants in the same way phantom types could.

**Comment by andmkent** [comment]
I think there's a good chance providing a more general backend for ``` define-new-subtype ``` with something resembling phantom types/fields in the future _would_ be an entirely painless process no end user would notice thanks to the way you implemented it. I am just a little paranoid there could be some _very subtle_ difference that would cause a few programs to type check in an ever-so-slightly different way, which would then leave us with the choice of breaking the programs w/ the new approach, or coming up with a way to continue support the old behavior (and if I'm not mistaken, we usually favor the latter). If we put a caveat in the docs noting the feature _may_ have a _slight_ change in the near future (but the goal is for it not to), then if we ended up deciding to risk breaking a few programs then at least there was a notice. Perhaps I'm being a little too paranoid with this concern.

Also (less important, probably), if the feature is later able to be implemented as a library, would it make more sense for it to be included in the default feature-set of "typed/racket" vs a library that is specifically for that feature? I don't have a real opinion related to this (or paranoia, hah), just a thought.

**Comment by AlexKnauth** [comment]
Ok, that makes sense.

**Comment by takikawa** [comment]
Thanks for the explanation, seems like it could be useful. So is the motivation for putting the phantomness in fields/objects is because that's a convenient place to put it? (because we have neither unification nor type constraints which are typically used to encode phantom types) Is there a deeper reason for why fields would be the "right" place to put these?

**Comment by andmkent** [comment]
@takikawa TBH I'm not 100% sure. I would lean towards thinking, if we already have as a fundamental notion of Typed Racket the concept of fields/paths, and if they naturally allow for a new feature (like phantom types, new subtypes, etc) with minimal additions and few changes to Typed Racket's internals, perhaps it's not only a convenient way to implement it, but a more desirable way in systems which are already utilizing occurrence typing. Of course, only time and experimentation will tell for certain... =)

**Comment by andmkent** [comment]
marked as experimental for now to be safe (commit 60c37ab)

**Comment by AlexKnauth** [comment]
Should that commit be put in the release branch as well?

**Comment by samth** [comment]
Yes, I'll do that.
