### ISSUE TITLE
Optimizer fails to handle 0+1.0i optimally

### ISSUE THREAD

**Issue by samth** [racket/typed-racket#237]
```
(lambda ([x : Float]) (* (random) x 0+1.0i))
```

The multiplication is not optimized. If you switch to `0.0+1.0i` it is optimized.

**Comment by stamourv** [comment]
That's the correct behavior.
Optimizing operations on complexes of mixed exactness leads to too early float conversions, which leads to giving different results than Racket.
I just fixed it this week.

**Comment by samth** [comment]
In which case can this produce the wrong answer?

**Comment by stamourv** [comment]
https://github.com/racket/typed-racket/commit/ca9306bb1d4f14f8ffad4aed66297c88717a650a#diff-d01483735246fe62bb31a6633b33e825R45

**Comment by stamourv** [comment]
More precisely, this would usually manifest as TR introducing NaNs where Racket would have inifinities, or zeroes.

**Comment by samth** [comment]
I'm still confused. What input has to be passed to that function to differentiate it from

```
(lambda ([x : Float]) (* (random) x 0.0+1.0i)
```

**Comment by stamourv** [comment]
That specific case is probably safe, but I was commenting on the general class of optimizations, which we used to do, but don't anymore because of the issue I explained above.
There's probably a subset of the mixed-exactness complexes for which this optimization may be safe, but our types can't distinguish them from the others.
