### ISSUE TITLE
unsafe-provide does not always eliminate boundaries

### ISSUE THREAD

**Issue by stamourv** [racket/typed-racket#289]
The following program spends ~45% of its time checking contracts, despite all the bindings it gets from typed code coming through `unsafe-provide`.

```
#lang racket

(module m typed/racket
  (require math/array typed/racket/unsafe)
  (unsafe-provide for/array array-ref))

(require 'm)

(define a (for/array ([i (in-range 10000)]) (+ i 1)))

(for ([i (in-range 10000)])
  (array-ref a (vector i)))
```

**Comment by samth** [comment]
There look to be two options here. One, the current behavior, where unsafe-provide is really like plain Racket's provide. Two, we change unsafe-provide to generate new runtime definitons, so that the reference to the array-ref identifier exported by math is not ever expanded in untyped code. The second doesn't seem like a great option, so maybe this should remain a documented limitation of unsafe-provide. But if you have an implementation idea that doesn't produce a new value level definition, then that seems like a better possibility.

**Comment by stamourv** [comment]
I suspect that "using the math library from untyped Racket" is one of the most common use cases for `typed/racket/unsafe`, so solution 1 is not satisfactory, IMO.

Can you elaborate on why you think solution 2 is not a great option?

**Comment by samth** [comment]
I think that if the math library wants to provide an unsafe interface, then that should be part of `math`. Is this issue a problem for implementing that, or just for doing it without changing `math`? We shouldn't be afraid of changing the library to add this interface.

Solution 2 isn't great because it's (a) costly in zo size -- lots of new definitions, (b) potentially bad for performance, since the optimizer now needs to see through more definitions, and (c) much more complex to implement (right now, `unsafe-provide` doesn't need to change anything about type checking, for example, nor does it need to worry about static struct info).

**Comment by stamourv** [comment]
So far, my motivation has been to add unsafety to `math` post-fact, in my own code.
But AFAICT, whether the module with the `unsafe-provide` is in the `math` library or in 3rd party code shouldn't matter, which would make this strategy not work to have `math` provide an unsafe interface.

**Comment by samth** [comment]
This program shows some easy ways to do what you want, I think:

```
#lang racket

(module m1 typed/racket
  (require math/array typed/racket/unsafe)
  (unsafe-provide for/array array-ref))

(module m2 racket
  (require (submod ".." m1))
  
  (define a (for/array ([i (in-range 10000)]) (+ i 1)))
  
  (time (for ([i (in-range 10000)])
          (array-ref a (vector i)))))

(module m3 typed/racket
  (require (prefix-in m: math/array) typed/racket/unsafe)
  (define array-ref m:array-ref)
  (unsafe-provide m:for/array array-ref))

(module m4 racket
  (require (submod ".." m3))
  
  (define a (m:for/array ([i (in-range 10000)]) (+ i 1)))
  
  (time (for ([i (in-range 10000)])
          (array-ref a (vector i)))))

(module m5 typed/racket
  (require (submod ".." m3))
  
  (define a (m:for/array ([i (in-range 10000)]) (+ i 1)))
  
  (time (for ([i (in-range 10000)])
          (array-ref a (vector i)))))

(require 'm2 'm4 'm5)
```

Unfortunately, the `m:for/array` macro still ends up inserting contracts, because of how the `math` library tries to work around Typed Racket. I think that code could probably be improved to make this work better.

**Comment by samth** [comment]
Note also that the last module in my example shows that the program actually spends 100% of its time in contracts.

**Comment by stamourv** [comment]
I don't understand. Why is `m4` faster than `m2`?
Re 100% in contracts: not exactly. 100% of `m2` and `m4`'s execution times are due to contract overhead, but a lot of it is not in contracts themselves (e.g. opportunity costs from the presence of contracts).

**Comment by stamourv** [comment]
(Also, why doesn't `unsafe-provide` do what `m4` does?)

**Comment by samth** [comment]
`m4` is faster than `m2` because `unsafe-provide` only affects things that defined in the current module. That's because the transformation to add contracts happens in the module the identifier (such as `array-ref`) is defined in, so `unsafe-provide` doesn't have the ability to disable it easily (since it already happened). 

As for why `unsafe-provide` doesn't do what `m4` does automatically, maybe it should. But note that the extra `define` isn't semantics-preserving in a variety of ways (starting with `free-identifier=?`). Of course, `unsafe-provide` already changes the `eq?` behavior of your program, for example, so maybe we shouldn't worry.

**Comment by stamourv** [comment]
Sounds like a good idea! I'll work on a patch.

**Comment by samth** [comment]
Another (probably better) possible implementation strategy: have `unsafe-provide` lookup the identifier using `syntax-local-value` and extract the typed identifier. This should be available using the data that's already there.

**Comment by stamourv** [comment]
I've started looking into it.
I'm not sure I see how `syntax-local-value` fits into the picture.
It also seems like `unsafe-provide` would have to go through the regular TR `provide` implementation to get the right info (i.e., can't just be skipping it and using Racket's provide directly, as it currently does).

**Comment by samth** [comment]
I think regular `provide` in TR defines the exported identifier to be one of these: https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/renamer.rkt#L15 and you should be able to get that out via `syntax-local-value`.

**Comment by stamourv** [comment]
Ok, that makes sense, and I think I've got it working that far. It doesn't seem happy with transformer bindings, though.
What about TR's info about what's a transformer binding and what's a value binding? Is that accessible too? Or is there some Racket function I'm missing?

**Comment by samth** [comment]
Well, you could do `syntax-local-value` on the target to try to get that info. But maybe TR should store that info in the renamer struct.

**Comment by bennn** [comment]
Just ran into this issue with some throw-away code, it was confusing that `unsafe-provide` didn't eliminate the type boundary.

I'm content that `unsafe-provide` doesn't add new definitions & I'd like to document this "limitation". But first @stamourv how is the patch?

**Comment by stamourv** [comment]
To a first approximation, it didn't go anywhere. You're welcome to pick it up.

**Comment by bennn** [comment]
Ok, I'll submit a docs patch and maybe an `unsafe-reprovide` syntax rule.

**Comment by bennn** [comment]
see https://github.com/racket/typed-racket/pull/657
