### ISSUE TITLE
Disallow : and type names as identifiers (?)

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#344]
This program compiles just fine. It defines a function of 3 arguments.

```
#lang typed/racket/base
(define (f (x : Integer) : String)
  (+ x 1))
```

But I wanted to define a function of 1 argument. What do people think about disallowing `:` and type names as identifiers?

I guess we could also print a warning or add a parameter like `allow-:-as-identifier`.

**Comment by lexi-lambda** [comment]
Oh, good. I can’t wait to put this at the top of my files:

```haskell
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
```

Seriously, though, using `:` as an identifier in TR *is* probably a mistake. A warning seems to make sense here to me.

**Comment by jsmaniac** [comment]
I quite agree, I'm often bitten by this when forgetting the extra pair of parenthesis.

Perhaps worth noting: I'm relying on `(provide (rename-out cln :))` to override the behaviour of `:` in my type-expander library (still ironing out a few bumps before packaging it). The same goes for Jack Firth's [compact annotations](http://docs.racket-lang.org/compact-annotations/index.html), which uses `::` but could easily be changed to override the default `:`. Libraries like these sound like a valid case for redefining `:`.

**Comment by andmkent** [comment]
You can take my ':' identifiers when you pry them from my cold, dead hands. /s

1) I agree it's probably an error in most (maybe all?) use cases, is there anywhere else in Racket where things are outright _disallowed_ because you can easily make a mistake?

2) In this case, the program may type check, but is this going to be a sneaky latent error that is impossible to debug? Or is it just going to immediately explode when you try and use it? I would assume the latter, but I haven't run into this particular issue so I'm guessing.

3) In other cases similar to this, I have found that good error messages can be the key to quickly addressing and fixing such mistakes. When you eventually get an error message, is it sufficient to figure out what's gone wrong? If not, maybe that would be the best thing to initially improve/fix?

**Comment by bennn** [comment]
`1.` No, I don't think so. You can even use `else` as an identifier in `match`. So disallowing ":" is probably the wrong thing.

```
    #lang racket
    (match #f
     [#t 0]
     [else
      (cond
       [(= 1 0) 1]
       [else    2])])
;; => #<void>
```

`3.` The error message I saw was similar to:
```
    wrong number of arguments provided
      expected: 3
      given: 1
      in: (f 1)
```

This was not too hard to debug, but annoying. If this error message included a warning that `f` used `:` as a parameter, I would have been less confused.

When handling an arity error, is it possible to:
- check whether we expected more arguments
- if so, check whether the missing arguments would be bound to `:` or a type name
- if so, include an extra warning in the exception?

Otherwise I'd like Typed Racket's `define` to print a warning if `:` is used as an identifier. Not sure if there's a protocol for doing that.

**Comment by samth** [comment]
Should `(lambda lambda lambda)` print a warning as well?

**Comment by lexi-lambda** [comment]
According to the very real GHC warning I alluded to above, some would say yes.

**Comment by andmkent** [comment]
"_Warning! Coworkers may physically harm you if you use the expression_```(lambda lambda lambda)``` _in actual code_"

**Comment by samth** [comment]
Right, there's a case for that warning in general. But I don't think that TR should have special warnings for its keywords.
