### ISSUE TITLE
Typed racket's `syntax->list` behaves differently than untyped racket's

### ISSUE THREAD

**Issue by jackfirth** [racket/typed-racket#347]
Racket version: 6.4

```racket
#lang typed/racket
(: f (-> Syntax (Option (Listof Syntax))))
(define (f stx) (syntax->list stx))
```

I think this should have typechecked successfully. Type error was:

```
Type Checker: Polymorphic function `syntax->list' could not be applied to arguments:
Argument 1:
  Expected: (Syntaxof (Listof a))
  Given:    Syntax

Result type:     (Listof a)
Expected result: (U False (Listof Syntax))
 in: (syntax->list stx)
```

Untyped racket's `syntax->list` function returns false when given non-list syntax objects, but the type of Typed Racket's `syntax->list` is `(All (a) (-> Syntaxof (Listof a) (Listof a)))` implying it can't be applied to non-list syntax objects at all. Is there a reason for this difference of behavior?

**Comment by AlexKnauth** [comment]
I think there used to be a case in the type for this, but it was removed because it was unsound. I forget the exact details, but it might have been something like `(syntax->list (ann #'(1 2 3) Syntax))` typechecking as `False`, which is wrong. It could be made sound by making that case return `(U False (Listof (Syntaxof Any)))` though, I think.

**Comment by AlexKnauth** [comment]
Yes, that's what the type of `stx->list` in `syntax/stx` does: 
https://github.com/racket/typed-racket/blob/master/typed-racket-more/typed/syntax/stx.rkt#L39
