### ISSUE TITLE
Bad optimization with `non-empty-string?`

### ISSUE THREAD

**Issue by jackfirth** [racket/typed-racket#426]
### What version of Racket are you using?

6.6

### What program did you run?

```racket
#lang typed/racket/base
(require racket/string)
(non-empty-string? "foo")
(non-empty-string? "")
(if (non-empty-string? "foo") 'A 'B)
(if (non-empty-string? "") 'A 'B)
```

### What should have happened?

Expected output: `#t #f 'A 'B`

Actual output: `#t #f 'A 'A`

Adding `#:no-optimize` fixes this.

**Comment by lexi-lambda** [comment]
It looks like this is likely an issue with the type of `non-empty-string?`. It currently has the type `(Boolean -> Any : String)`, but it should have the type `(Boolean -> Any #:+ String)`.

**Comment by wargrey** [comment]
Hi, I added this annotation with the constructor `make-pred-ty` just like the way other predicators are annotated in the codebase.

In fact, I have found this questions too.
As I thought, `: Type` should behave like `: #:+ Type` since the `: #:- Type` branch just exists for logical completeness. However in practice, I occasionally met some cases that `: Type` does not work while `: #:+ Type` does. Hence, now I always annotate my function with `#:+`.

My fault if this is the root cause.

**Comment by AlexKnauth** [comment]
I tested @lexi-lambda's comment with this program:
```racket
#lang typed/racket/base
(require racket/string)
(: non-empty-string*? : (-> Any Boolean : #:+ String #:- (! String)))
(define (non-empty-string*? v)
  (non-empty-string? v))
(non-empty-string*? "foo")
(non-empty-string*? "")
(if (non-empty-string*? "foo") 'A 'B)
(if (non-empty-string*? "") 'A 'B)
```
This produces the same buggy behavior as the original example, and it returns to normal if I take away the `#:- (! String)` filter.

So the solution is just like @lexi-lambda said: the type should be `(-> Boolean Any : #:+ String)`
