### ISSUE TITLE
Bad error messages in “typed/rackunit”

### ISSUE THREAD

**Issue by leafac** [racket/typed-racket#463]
### What version of Racket are you using?

6.7.

### What program did you run?

```
#lang typed/racket
(require typed/rackunit)
 
(check-not-false (= 1 2))

=>

    - : Any

    --------------------
    FAILURE
    name:       check-not-false
    location:   (#<path:/home/pasterack/racket66/share/pkgs/typed-racket-more/typed/rackunit/main.rkt> 41 2 907 15)
    expression: (check-not-false expr129)
    params:     (#f)
    Check failure
    --------------------
```

### What should have happened?

1. `location` should point to the failed assertion.
2. `expression` should contain the original expression.

The following **untyped** program illustrates the expected output:

```
#lang racket
(require rackunit)
 
(check-not-false (= 1 2))

=>

    --------------------
    FAILURE
    name:       check-not-false
    location:   (eval 2 0 2 1)
    expression: (check-not-false (= 1 2))
    params:     (#f)
    Check failure
    --------------------
```

**Comment by jsmaniac** [comment]
@leafac I have implemented some wrappers in [my personal toolkit](https://github.com/jsmaniac/phc-toolkit/blob/master/typed-rackunit.rkt#L39) (see https://github.com/racket/typed-racket/issues/54#issuecomment-244732072 for another issue that these wrapper solve).

As a quick fix, you can use `(require phc-toolkit/typed-rackunit)`, although I haven't overridden all forms from `typed/rackunit` yet.

```racket
#lang typed/racket/base

(require phc-toolkit/typed-rackunit)

(check-not-false: (= 1 2))

=>

    --------------------
    FAILURE
    actual:     "#f"
    expected:   "#t"
    name:       check-not-false:
    location:   (unsaved-editor 5 0 64 26)
    expression: (check-not-false: (= 1 2))
    
    Check failure
    --------------------
```

If you are willing to merge these into `typed/rackunit`, it would be great! Otherwise I'll do it eventually, but I don't have enough time right now.

**Comment by leafac** [comment]
Thanks a lot for the workaround, @jsmaniac. I’ll try to turn your code into a Pull Request for Typed Racket.

**Comment by wanderley** [comment]
I still can repro this issue.

```
--------------------
; FAILURE
; /Applications/Racket v7.1/share/pkgs/rackunit-typed/rackunit/main.rkt:18:2
name:       check-eq?
location:
  /Applications/Racket v7.1/share/pkgs/rackunit-typed/rackunit/main.rkt:18:2
actual:     1
expected:   2
--------------------
```

**Comment by samth** [comment]
I don't think this is actually fixed yet.

**Comment by capfredf** [comment]
closed in https://github.com/racket/rackunit/pull/153
