### ISSUE TITLE
expansion of 'if' goes off the rails in certain circumstances

### ISSUE THREAD

**Issue by jbclements** [racket/typed-racket#515]
### What version of Racket are you using?

6.8.0.2--2017-03-20(-/f) [3m]. (Git head as of this morning)

### What program did you run?

This bug appears to require two files.

In file "a.rkt":

```racket
#lang typed/racket
(define left-element car)
(provide left-element)
```

In file "b.rkt":

```racket
#lang typed/racket
(require "a.rkt")
(if (eq? 1 (left-element (cons 1 2)))
    "Equal"
    "Not Equal")
```

### What should have happened?

Evaluating "b.rkt" should result in the value "Equal." Instead, it printed "#t".

I took a look at the fully expanded form of the program using the macro stepper, and I see this:

```racket
(if
 '#t
 (#%app:57
  eq?
  (quote 1)
  (#%app:58 left-element (#%app:59 cons (quote 1) (quote 2))))
 (begin (quote "Equal") (quote "Not Equal")))
```

It looks to me as though the optimizer is discovering that this test is guaranteed to succeed, but that rather than replacing the test with #t, it's somehow just inserting it. Maybe the test is supposed to be kept for possible mutations? Not sure. Either way, it's definitely not going to return "Equal" as it should.

It's definitely a combination of a few things, though... replacing 'left-element' with 'car' makes the problem disappear.

(NB: bug discovered by Jono Chadwell. Thanks, Jono!)

**Comment by pnwamk** [comment]
It's not an optimizer bug -- the type checker believes the result of the application of the function application is Bottom. I'm looking into it.

Side note: perhaps the optimizer should do something different when it believes a test expression in an `if` is an error (perhaps insert an "unreachable" error that would blow up and report that TR incorrectly typechecked something so users at least know who to complain to when their program goes wonky)?

**Comment by pnwamk** [comment]
I've identified the bug that caused this issue and am writing a fix and tests in a bit. 

As an aside -- currently if we think _both_ branches of an `if` are unreachable, we optimize it into the following:
`(if #t tst.opt (begin thn-opt els-opt))`

Would it be better to optimize it into something like the following:

`(begin tst.opt (error 'typed-racket "unreachable if body!")`

so users whose programs hit a bug in the type checker that generates this code when it is not warranted will get an explicit error instead of weird, non-obvious issues in their program?

Thoughts @samth @stamourv ?


P.S. the code that optimizes `if`s the way I mentioned above is found [here](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/optimizer/dead-code.rkt#L33)

**Comment by mfelleisen** [comment]
> On Mar 20, 2017, at 7:04 PM, Andrew Kent <notifications@github.com> wrote:
> 
> I've identified the bug that caused this issue and am writing a fix and tests in a bit.
> 
> As an aside -- currently if we think both branches of an if are unreachable, we optimize it into the following:
> (if #t tst.opt (begin thn-opt els-opt))
> 
> Would it be better to optimize it into something like the following:
> 
> (begin tst.opt (error 'typed-racket "unreachable if body!")
> 
> so users whose programs hit a bug in the type checker that generates this code when it is not warranted will get an explicit error instead of weird, non-obvious issues in their program
> 
> 

The second option is much better.

**Comment by stamourv** [comment]
@pnwamk: Adding the error sounds good to me. But you should keep the `if` that is currently generated (with unreachable else clause), if only for tooling.
