### ISSUE TITLE
Strange behavior of inst in the righthand side of let

### ISSUE THREAD

**Issue by yjqww6** [racket/typed-racket#561]
### What version of Racket are you using?
6.9
### What program did you run?
```
(let ([a (inst cons Integer Integer)])
    (cons #f #f))
```
### What should have happened?
```
- : (Pairof False False)
'(#f . #f)
```
### If you got an error message, please include it here.
```
 Type Checker: type mismatch
  expected: Integer
  given: False in: #f
```

The letrec version works as expected:
```
> (letrec ([a (inst cons Integer Integer)])
    (cons #f #f))
- : (Pairof False False)
'(#f . #f)
```

**Comment by yjqww6** [comment]
I'm not so familiar with typed-racket internals, but I believe let-aliasing and the fact that `(inst e ...)` carries the same objects as `e` cause the problem.

Is this right? Should `inst` forms carry empty objects?

I have tried changing https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/tc-expression.rkt#L63
from ` (ret (list (inst-type ty inst)) fs os)]` to ` (ret (list (inst-type ty inst)) fs '(#f))]` , and the bug seems disappeared.

**Comment by pnwamk** [comment]
You are absolutely correct about that being a sound solution in this case (sound as in type sound), but my knee-jerk response is that we shouldn't have to throw away the object since the original type for `cons` is more specific than (a subtype of) the instantiated function type... I'll take a peek at what's going on this weekend and see if I can't see why it doesn't just work as is and report.
