### ISSUE TITLE
Unsound static contracts optimization

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#598]
The static contracts optimizer converts `(or/sc _ ... any/sc _ ...)` to `any/sc`. This is only sound if the `_ ...` contracts are flat.

I'm planning to fix this in #575,
but posting the issue to get feedback on my "only sound if" claim above.

### What version of Racket are you using?

Tested on 6.7 and HEAD

### What program did you run?

```
#lang typed/racket/base

(module u racket/base
  (define (f b)
    (set-box! b "hello"))
  (provide f))

(define-type Maybe-Box (U #f (Boxof Integer)))

(require/typed 'u (f (-> Maybe-Box Void)))

(define b : Maybe-Box (box 4))
(f b)

(if (box? b)
  (+ 1 (unbox b))
  (error 'deadcode))
```

### What should have happened?

Contract violation at the `set-box!` call.

### If you got an error message, please include it here.

```
+: contract violation
  expected: number?
  given: "hello"
  argument position: 2nd
  other arguments...:
   1
```

**Comment by rfindler** [comment]
That sounds right to me (but I don't know what the `s`s are in the middle of the contract names).

**Comment by samth** [comment]
@rfindler `any/sc` and `or/sc` are the names of AST constructors for TR's AST for generating contracts. They generate the obvious contracts, modulo optimization passes.

**Comment by bennn** [comment]
This is harder to fix than I thought.

First idea: optimize `(or/sc x ... any/sc y ...)` to `(or/sc any/sc z ...)` where `(z ...)` is the result of `(filter not-flat? (x ... y ...))`. But that makes an `(or/c any/c z ...)`, which accepts any value.

Second idea: optimize to `(or/sc (and/sc (not z) ...) z ...)`. This is hard to do because `not/c` requires a flat contract --- I'm not sure if I can get a flat contract from any `sc` contract.

Third idea: avoid getting an `(or/sc x ... any/sc y ...)` in the first place if any of the `(x ...)` or `(y ...)` is not flat. But this seems hard to do with the way the optimizer is set up to use `sc-map` --- it uses a map function with type `(-> sc variance sc)` so the function can't tell that the `sc` it's currently optimizing is the child of an `or/sc` and has a non-flat sibling.

I tried the 3rd idea today, planning to try the 2nd next time.

**Comment by AlexKnauth** [comment]
Does `any/sc` not protect boxes from mutation when crossing from typed to untyped?

**Comment by rfindler** [comment]
Actually, I think that what I wrote earlier was confused. I think that the "only sound if" claim is wrong. (That said, I am talking just about contracts, not about types.)

The program below does not raise an error, it produces `#f`. The contract system doesn't specially optimize this case, but the it doesn't do very much work either (it does do the `any/c` check before the arrow contract's first-order checks, and then always skips those).

```
#lang racket
(define (f1 x) x)
(define f2
  (contract (or/c (-> integer? integer?)
                  any/c)
            f1
            'pos 'neg))

(f2 #f)
```

**Comment by bennn** [comment]
@AlexKnauth nope, `any/sc` just means "put an `any/c` contract here. For example, if a TR module is exporting a function with type `(-> Symbol Symbol)` then its safe to give it the contract `(-> symbol? any/c)`.

(I should look at what TR does for `->` returning higher-order values.)

@rfindler that makes sense, I agree the contract system isn't doing anything wrong.

**Comment by AlexKnauth** [comment]
So is there an `any-wrap/sc` it should use to safely protect higher-order values in cases like this?

**Comment by pnwamk** [comment]
Does this program also illustrate the same problem?

```racket
#lang racket/base

(module t typed/racket/base
  (define-type Maybe-IntBox (U #f (Boxof Integer)))
  (define b : Maybe-IntBox (box 42))
  (provide b))

(require 't)

(set-box! b "42")
```

(sorry, I'm coming into this a little late and just trying to understand the root of the problem.)

**Comment by pnwamk** [comment]
So in our static-contract (sc) intermediate language, what does `any/sc` mean?

My knee jerk reaction is to want to just assign it the same meaning that `any/c` has: _"A flat contract that accepts any value."_  But thats clearly wrong, e.g. when we optimized the contract for `False` into `any/sc`, we didn't mean "this can be any value", we meant "oh TR doesn't need to do anything interesting to protect this value".

I guess I'm wondering "is the or/sc optimization wrong?" (as in, that's the only problem), or is there  a subtle problem with how we interpret `any/sc` (and are we making mistakes when we work with it because we're wanting to treat it more like `any/c` than it really is? is there a better name? (e.g. `no-need-to-check/sc`))? (or maybe both?)

Sorry if this doesn't make any sense or I'm going off on an unhelpful tangent.

**Comment by bennn** [comment]
What you're saying makes sense, and your program also illustrates the problem, and what you're wondering makes sense too given the issue title.

I gave a bad title/description.

The `(U flat-type non-flat-type)` programs are definitely a problem, but the `(or/sc _ ... any/sc _ ...)` optimization is NOT the cause.

The real problem is changing `(or/sc flat/sc chaperone/sc)` to `(or/sc any/sc chaperone/sc)`. It should really be `(or/sc chaperone/sc anything-else/sc)`.

Anyway, #599 turns off the optimizer for `or/sc`s that contain non-flat contracts.

**Comment by samth** [comment]
I think just turning off the optimizer is not necessarily sufficient. We need to make sure that all of the possibilities in `or/sc` are actually considered, even after translation to contracts, and therefore we should probably never generate `(or/c any/c other/c ...)`. Is that the case after #599?

**Comment by bennn** [comment]
#599 makes sure we never generate an `(or/c any/c other/c ...)` when one of the `other/c ...` is non-flat.

(Otherwise, if all the `other/c` are flat and the contract appears in a "trusted positive" position, then the optimizer reduces the whole `or/c` to an `any/c`.)

Not sure that means all cases are considered ... there might be a case where we have a `(or/c flat/c chap/c)` and the `flat/c` accepts a value that should be chaperoned. (I'll think more about this.)

**Comment by pnwamk** [comment]
Hey! So I chatted with Sam about this generally today, here are some notes from our discussion:

+ We do want `any/sc` to mean `any/c` -- they shouldn't be inherently different.
+ As for avoiding the problem mentioned in this PR, it seems like the heart of the issue is when we are allowing flat contracts to be turned into `any/sc`. The following rule for optimizing flat static contracts  we think should suffice:

_(Note: the following is just an intuitive sketch -- the function names and struct names are probably all wrong)_

`(optimize/sc a-flat-static-contract)`

should be transformed into `any/sc` if and only if (1) we are in a "trusted positive" position (this is not new, this is what it did before) and (2) if we are not currently in a disjunction (i.e. an `or/sc`).

otherwise it should be left as `a-flat-static-contract`

For keeping track of if we are under a disjunction, that would probably be easy to track with a parameter (at least that wouldn't require reworking the interfaces to the current functions), and we are no longer under a disjunction if we pass under a "real" type constructor (e.g. a function, a pair, etc).

**Comment by bennn** [comment]
I agree conditions (1) and (2) are safe. But I think (2) is too strong, 
- I think it's safe to optimize `(or/sc string? integer?)` to `any/sc` in a trusted positive position
- generally, I think it's safe to turn any `(or/sc a-flat-static-contract ...)` in a trusted positive position into an `any/sc`

Do you and Sam like how #599 checks for disjunctions?

**Comment by pnwamk** [comment]
I agree, because we should interpret `(or/sc string? integer?)` as a flat static contract:

```racket
(flat-contract? (or/c string? integer?))
; ==> #t
```

Off the top of my head I don't remember how thorough our ability to ask "is this a flat static contract" is. Perhaps that needs a little work as well?

**Comment by bennn** [comment]
Okay, I updated #599 to look for `(or/sc flat-contract? ...)` and turn it into an `any/sc`.

**Comment by bennn** [comment]
https://github.com/racket/typed-racket/commit/9df037b0f6e6b2df3cc0993631bb2870367e291a
