### ISSUE TITLE
TR signals error inconsistently on match with value after ellipsis

### ISSUE THREAD

**Issue by jbclements** [racket/typed-racket#660]
### What version of Racket are you using?

git head: 6.12.0.3--2018-02-01(-/f) [3m]

### What program did you run?

Program A:

```racket
#lang typed/racket

; Translates var expressions into lam expressions.
(define (var-to-lam [s : Sexp]) : Sexp
  (match s
    [(list 'func (? list? arg) ...)
     13]))
```

Program B (has 'body' at end of match pattern):

```racket
#lang typed/racket

; Translates var expressions into lam expressions.
(define (var-to-lam [s : Sexp]) : Sexp
  (match s
    [(list 'func (? list? arg) ... body)
     13]))
```

### What should have happened?

1) Both should behave the same (the only difference is the unused `body` at the end of the pattern.
2) Neither one should signal a type error.

### If you got an error message, please include it here.

Program A: no error.

Program B:
```
Type Checker: type mismatch
  expected: (-> Nothing)
  given: (-> Sexp) in: (match s ((list (quote func) (? list? arg) ... body) 13))
```

**Comment by samth** [comment]
Unfortunately, these two programs, while superficially similar, are quite different when expanded. So Typed Racket can't make them "behave the same" in any way that would be helpful (it could reject every `match` that used `...`, but that wouldn't be better).

**Comment by jbclements** [comment]
Can you help me understand the type error? Specifically, I'm trying to figure out how to tell my students to get from the given error message to the solution, which is apparently to add an "else" case. "When in doubt, add an else case?" seems a bit broad, but maybe that's the intuition?

**Comment by samth** [comment]
The type error happens as follows:

- `match` implements `...` with a recursive function that takes a continuation function to call when it gets to the end (here the end is with one element left). The initial value of that continuation is a function that always raises a `match` error, which has type `(-> Nothing)` since it never returns. The `... body` pattern passes a different continuation function later, which doesn't have that type (because it can succeed and run the RHS when you get to the end, by matching the last element). Since we inferred the type of the continuation argument from that initial value, we can't apply the recursive function to this new argument, and we get a type error.

- if you add an else clause, then the initial value of that continuation is basically "do the else clause". That's inferred to have a different type, based on what you actually put in the else clause.

- Somewhat surprisingly to me, even if there's a call to `error` in the else clause, it still works, but I'm not yet sure why.

Unfortunately, I don't have a good intuition to provide for your students. `match` output is complicated, and TR tries hard enough to do pretty well, but doesn't quite get this case.

**Comment by samth** [comment]
Yes, that's correct -- unannotated mutable variables and function arguments get handled with a bunch of heuristics, which aren't succeeding here. Of course, the relevant function argument is macro generated, so you can't add an annotation yourself.

However, I just realized that there's yet another trick that should be helping here, but isn't. I'll look more soon.

**Comment by samth** [comment]
Turns out one place in `match` wasn't helping one of TR's pile of heuristics in the right way, so this is fixable.

There are probably similar programs that still won't work, but this one is fixable.

**Comment by jbclements** [comment]
That's wonderful! May I reopen this issues?
