### ISSUE TITLE
tooltips are inconsistent

### ISSUE THREAD

**Issue by rfindler** [racket/typed-racket#666]
### What version of Racket are you using?
6.12.0.3.

### What program did you put in the definitions window?

```
#lang typed/racket

(: f (-> (U String Number) String))
(define (f x)
  (if (string? x) x (number->string x)))
```

### What should have happened?

Probably none of the tooltips should have said "complex" in them. But certainly it should be the case that they should consistently use either number or complex instead of having the last occurrence of `x` say `Number` and the third to last say `(U Complex String)`

### If you got an error message, please include it here.

No error message.

**Comment by rfindler** [comment]
This might be a different issue than the above program, but I'll include here anyway. Let me know if you would prefer me to separate it out.

In this program, the last two occurrences of `x` don't get a tooltip type. (They also don't get one if you use them in some less obviously bad way.)

```
#lang typed/racket #:no-optimize

(: plus (-> (U String Integer)
            (U String Integer)
            (U String Integer)))
(define (plus x y)
  (cond
    [(and (number? x) (number? y))
     (+ x y)]
    [(number? x)
     (string-append
      (format "~a" x)
      (format "~a" y))]
    [(string? x)
     (string-append
      (format "~a" x)
      (format "~a" y))]
    [else
     (+ x (car x))]))
```

**Comment by samth** [comment]
These are indeed two different problems. The first issue is the same as #470 and #395, a long-standing bug that I haven't yet figured out a good way to fix, because it's based on some key decisions about how type names work that probably weren't the right ones. The second issue is that the type checker doesn't even look at that expression, since it's definitely unreachable, but there should definitely be a tooltip indicating that.

**Comment by rfindler** [comment]
alright, refactoring issues.
