### ISSUE TITLE
regression: optional arguments

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#710]
### What version of Racket are you using?

<https://github.com/racket/typed-racket/commit/4b1a1bfa9d59aa2ae469e1217dd16aea9c2f5aa6>

### What program did you run?

```
#lang typed/racket/base

(: f (-> String String))
(define (f a [b ""])
  (string-append a b))
```

### What should have happened?

The program should type-check, possibly via:
- assume `a : String`
- infer `b : String`
- infer `f : (->* (String) (String) String)`
- check `(->* (String) (String) String) <: (-> String String)`
- success

### If you got an error message, please include it here.

```
Type Checker: type mismatch
  expected: String
  given: Any
  in: a
.... (clipped) ....
```

**Comment by AlexKnauth** [comment]
The type of `a` should be less connected to the "outside" type. It comes from either the "outside" or from the default-expr. Here are two programs that show what I mean.

###### Program 1:
```racket
(: f (-> Integer))
(define (f [x 0])
  x)
```
Here the type of `x` in the body doesn't come from the outside, it comes from typechecking the `default-expr`, which is `0` with type `Zero`. That's why the type of `x` in the body is `Zero`.

###### Program 2:
```racket
#lang typed/racket
(: f (->* [] [Integer] (U Integer False)))
(define (f [x #false])
  x)
```
Here the type of `x` in the body doesn't come directly from the outside either. It comes from either the outside or the `default-expr`, so it is the union of those two types, `Integer` and `False`.

###### The new expansion and how it relates to TR
According to [racket/private/kw.rkt](https://github.com/racket/racket/commit/662a9022c0858f1de69712c31ce520bc80930fa3#diff-36cf40d20fdf98bdddffc0e7dc0c01edR44), Program 1 will expand to something like this: 
(if it treats 0 as if it was an arbitrary expression instead of a literal)
```racket
(: f (-> Integer))
(define f
  (let ([core
         (lambda (_x)
           (let* ([x (if (eq? _x unsafe-undefined)
                         0
                         _x)])
             ; body
             x))])
    (case-lambda
      [() (core unsafe-undefined)]
      [(x) (core x)])))
```
Here we see where the `Any` might come from: the `_x`. Typed Racket needs to recognize that `_x` always comes from either the "outside" if there is one, or `unsafe-undefined`. 

If the type annotation `(: f (-> Integer))` doesn't include that argument, there is no way to get an `_x` from "outside". So the type of `_x` should be just a singleton `unsafe-undefined`, meaning the type of `x` should be `Zero`.

###### The original program:
```
(: f (-> String String))
(define (f a [b ""])
  (string-append a b))
```
This is more like program 1. Just like the type of `x` should come from the `0`, the type of `b` should come from the `""`, and be `String`.
