### ISSUE TITLE
type checking program with flatten

### ISSUE THREAD

**Issue by akcheung** [racket/typed-racket#754]
### What version of Racket are you using?
6.12

### What program did you run?
(: l1 (Listof Integer))
(define l1 (list 1 2 3))
(: l2 (Listof Integer))
(define l2 (flatten l1))

### What should have happened?
I'm wondering if there is a way to get the above program type check? Can I add an explicit cast somehow?

### If you got an error message, please include it here.
Type Checker: type mismatch
  expected: (Listof Integer)
  given: (Listof Any) in: (flatten l1)

**Comment by mfelleisen** [comment]
```
#lang typed/racket

(: l1 (Listof Integer))
(define l1 (list 1 2 3))
(: l2 (Listof Integer))
(define l2 (cast (flatten l1) [Listof Integer]))
```

But it's better to ask this on our mailing lists.

**Comment by samth** [comment]
Unfortunately `flatten` needs more sophisticated types than TR supports to give a reasonable type, because the list element type could itself be a list. With negation types, we could allow this (cc @pnwamk) but for the moment an explicit check as @mfelleisen describes is the best option. 

Note that `(assert (flatten l1) (lambda ([e : (Listof Any)]) (andmap exact-integer? e)))` will be faster if you call this a lot.
