### ISSUE TITLE
Error when casting `(seteq)` to `(Setof _)` type

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#814]
### What version of Racket are you using?
`7.2`
### What program did you run?
```racket
#lang typed/racket

(struct S ([elems : (Setof Symbol)]) #:transparent)

(cast (ann (S (seteq)) Any) S)
; struct-ref: non-chaperone result;
;  received a result that is not a chaperone of the original result
;   original: (seteq)
;   received: (set)

(cast (ann (seteq) Any) (Setof Symbol))
; make-chaperone-contract::late-neg-projection: contract violation
;   expected: chaperone-of (seteq)
;   received: (set)
```
### What should have happened?

The casts should succeed. The `Any` annotation emulates when elements are pulled out of the `...` pattern in `match`, or when the value flows from untyped. 

For the first cast, would a tag check have been enough, since the instantiation of `S` is controlled by the typed module?

**Comment by AlexKnauth** [comment]
The problem is probably coming from the definition of `any-wrap/c` on sets, on lines 174-177 of "any-wrap.rkt":
```
      [(? set?) 
       (for/set ([i (in-set v)]) (any-wrap/traverse i neg-party))] 
```
https://github.com/racket/typed-racket/blob/ade0dff65ed89c435205c5bfc17fee7f0837083c/typed-racket-lib/typed-racket/utils/any-wrap.rkt#L174-L177

Most of the other pieces of code around it attempt to use chaperones, but for Sets and Hash Tables, it's different.
https://github.com/racket/typed-racket/blob/ade0dff65ed89c435205c5bfc17fee7f0837083c/typed-racket-lib/typed-racket/utils/any-wrap.rkt#L138-L148

A Hash Set is basically a hash table where the only thing that matters is the keys, and the comments on the hash-table code highlight a problem with wrapping the keys while preserving chaperone stuff.

I don't understand why this is a problem though, since `chaperone-hash-set` seems to do this, although it does have behavior like `(set-member? (set-add S add1) add1)` returning false if `S` is a `set-eq?` that uses a chaperone, it never causes a type safety issue.

**Comment by philnguyen** [comment]
I meant to say the `Any` annotation, though contrived, was just an attempt to emulate the loss of type information when I used `...` in `match` before casting the value list to `(Listof _)`.

```racket
(: inits : (Listof (Setof Symbol)) → (Listof Symbol))
(define inits
  (match-lambda
    [(list xs ... _) (cast xs (Listof Symbol))]))

(inits (list (seteq) (seteq)))
```
If part of the type is known, this error won't happen:
```racket
(cast (assert (ann (seteq 'foo 'bar) Any) set?) (Setof Symbol)) ; ==> ok
(cast         (ann (seteq 'foo 'bar) Any)       (Setof Symbol)) ; ==> error
```

**Comment by AlexKnauth** [comment]
Would something like this solve this problem?
https://github.com/racket/typed-racket/compare/master...AlexKnauth:any-wrap-set-chaperone
```
      [(? set?) (chaperone-hash-set
                 v
                 (λ (s e) e) ; inject
                 (λ (s e) (if (immutable? v)
                              e
                              (fail neg-party v))) ; add
                 (λ (s e) e) ; remove
                 (λ (s e) (with-contract-continuation-mark
                           blame+neg-party
                           (any-wrap/traverse e neg-party))))] ; extract
```

**Comment by AlexKnauth** [comment]
Are there any further issues after #816, or should this be closed?
